version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    assignees:
      - "VMelnalksnis"
    reviewers:
      - "VMelnalksnis"
    groups:
      avalonia:
        patterns:
          - "Avalonia*"
      microsoft:
        patterns:
          - "Microsoft*"
      npgsql:
        patterns:
          - "Npgsql*"
      nunit:
        patterns:
          - "NUnit*"
      otel:
        patterns:
          - "OpenTelemetry*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    assignees:
      - "VMelnalksnis"
    reviewers:
      - "VMelnalksnis"

  - package-ecosystem: "npm"
    directory: "/source/Gnomeshade.WebApi/Node"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    versioning-strategy: "increase"
    assignees:
      - "VMelnalksnis"
    reviewers:
      - "VMelnalksnis"
