---
dependencies: [ ]
galaxy_info:
  author: Valters Melnalksnis
  namespace: gnomeshade
  description: Installs Gnomeshade
  company: Gnomeshade
  license: AGPL-3.0-or-later

  min_ansible_version: '2.1'

  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy

  galaxy_tags:
    - gnomeshade
