name: 'ReSharper inspection annotations'
description: 'Annotates code with ReSharper inspections'
inputs:
  report:
    description: 'Filepath of the ReSharper inspection report'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.report }}
