- name: Create directories
  become: true
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ gnomeshade_user }}'
    group: '{{ gnomeshade_group }}'
    mode: '0750'
  with_items:
    - '{{ gnomeshade_install_directory }}'
    - '{{ gnomeshade_config_directory }}'

- name: Download Gnomeshade
  get_url:
    url: '{{ gnomeshade_binary_url }}'
    dest: '/tmp/gnomeshade_linux-x64.zip'
    owner: '{{ gnomeshade_user }}'
    group: '{{ gnomeshade_group }}'
    mode: '0640'

- name: Extract files to installation directory
  become: true
  unarchive:
    src: '/tmp/gnomeshade_linux-x64.zip'
    dest: '{{ gnomeshade_install_directory }}'
    remote_src: yes
    owner: '{{ gnomeshade_user }}'
    group: '{{ gnomeshade_group }}'
    mode: '0640'

- name: Rename executable
  become: true
  copy:
    src: '{{ gnomeshade_install_directory }}/Gnomeshade.Interfaces.WebApi'
    dest: '{{ gnomeshade_install_filepath }}'
    remote_src: yes
    owner: '{{ gnomeshade_user }}'
    group: '{{ gnomeshade_group }}'
    mode: '0750'
  notify:
    - Restart gnomeshade

- name: Remove original executable
  become: true
  file:
    path: '{{ gnomeshade_install_directory }}/Gnomeshade.Interfaces.WebApi'
    state: absent

- name: Create configuration
  become: true
  template:
    src: 'templates/appsettings.json.j2'
    dest: '{{ gnomeshade_config_filepath }}'
    owner: '{{ gnomeshade_user }}'
    group: '{{ gnomeshade_group }}'
    mode: '0640'
  notify:
    - Restart gnomeshade

- name: Create service unit
  become: true
  template:
    src: 'templates/gnomeshade.service.j2'
    dest: '/etc/systemd/system/gnomeshade.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - Reload gnomeshade
    - Restart gnomeshade
