#!/bin/bash

adduser --system --no-create-home --home /nonexistent --disabled-login --shell=/bin/false gnomeshade || exit

chown gnomeshade /etc/opt/gnomeshade --recursive || exit
chown gnomeshade /opt/gnomeshade --recursive || exit

systemctl daemon-reload || exit
systemctl enable gnomeshade.service || exit
