#!/bin/bash
set -e

GNOMESHADE_USER=gnomeshade

if [[ -z "$(getent group ${GNOMESHADE_USER})" ]]; then
	addgroup --system ${GNOMESHADE_USER}
fi

if [[ -z "$(getent passwd ${GNOMESHADE_USER})" ]]; then
	adduser \
		--system --ingroup ${GNOMESHADE_USER} ${GNOMESHADE_USER} \
		--no-create-home --home /nonexistent \
		--gecos "Gnomeshade default user"
fi

chown gnomeshade /etc/opt/gnomeshade --recursive
chown gnomeshade /opt/gnomeshade --recursive

deb-systemd-invoke enable gnomeshade.service
