//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnomeshade.Core.Tests.Imports.Fidavista {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestFiles {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestFiles() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gnomeshade.Core.Tests.Imports.Fidavista.TestFiles", typeof(TestFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Statements_xml {
            get {
                return ResourceManager.GetString("Statements.xml", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;FIDAVISTA xmlns=&quot;http://ivis.eps.gov.lv/XMLSchemas/100017/fidavista/v1-2&quot;&gt;
        ///    &lt;Statement&gt;
        ///        &lt;Period&gt;
        ///            &lt;StartDate&gt;2021-01-01&lt;/StartDate&gt;
        ///            &lt;EndDate&gt;2021-07-24&lt;/EndDate&gt;
        ///            &lt;PrepDate&gt;2021-07-24&lt;/PrepDate&gt;
        ///        &lt;/Period&gt;
        ///        &lt;AccountSet&gt;
        ///            &lt;AccNo&gt;LV42PARX0013733920001&lt;/AccNo&gt;
        ///            &lt;CcyStmt&gt;
        ///                &lt;Ccy&gt;EUR&lt;/Ccy&gt;
        ///                &lt;OpenBal&gt;2493.85&lt;/OpenBal&gt;
        ///                &lt;CloseBal&gt;1930. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Statementv2 {
            get {
                return ResourceManager.GetString("Statementv2", resourceCulture);
            }
        }
    }
}
