name: build and test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2.1.0

      - name: Cache NuGet packages
        uses: actions/cache@v3.0.8
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.2.3
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('**/WebserverSetup.cs') }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: >
          dotnet build 
          --configuration Release 
          --no-restore
          /warnAsError
          /nologo
          /clp:NoSummary

      - name: Run Tests
        run: >
          dotnet test
          -p:CollectCoverage=true
          -p:CoverletOutput=TestResults/
          -p:CoverletOutputFormat=opencover
          -p:BuildInParallel=true
          -m:8
          --configuration Release
          --no-build
        env:
          Nordigen:SecretId: ${{ secrets.NORDIGEN_SECRET_ID }}
          Nordigen:SecretKey: ${{ secrets.NORDIGEN_SECRET_KEY }}
          Serilog:MinimumLevel: Warning

      - name: Gather Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  resharper:
    name: Resharper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2.1.0

      - name: Cache NuGet packages
        uses: actions/cache@v3.0.8
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore /warnAsError /nologo /clp:NoSummary

      - name: ReSharper annotations
        uses: VMelnalksnis/resharper-inspect-action@v0.2.3
        with:
          solution: Gnomeshade.sln
          resharper-version: 2022.1.2
          treat-warnings-as-errors: true
