name: build and test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-dotnet@v3.0.2
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'source/Gnomeshade.WebApi/Node/package-lock.json'

      - name: Cache NuGet packages
        uses: actions/cache@v3.0.10
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - run: dotnet restore --locked-mode /p:Configuration="Release"

      - name: Build
        run: >
          dotnet build 
          --configuration Release 
          --no-restore
          /warnAsError
          /nologo
          /clp:NoSummary

      - name: Run Tests
        run: >
          dotnet test
          -p:CollectCoverage=true
          -p:CoverletOutput=TestResults/
          -p:CoverletOutputFormat=opencover
          -p:BuildInParallel=true
          -m:8
          --configuration Release
          --no-build
        env:
          Nordigen:SecretId: ${{ secrets.NORDIGEN_SECRET_ID }}
          Nordigen:SecretKey: ${{ secrets.NORDIGEN_SECRET_KEY }}
          Serilog:MinimumLevel: Warning

      - name: Gather Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  resharper:
    name: Resharper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-dotnet@v3.0.2
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'source/Gnomeshade.WebApi/Node/package-lock.json'

      - name: Cache NuGet packages
        uses: actions/cache@v3.0.10
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - run: dotnet restore --locked-mode /p:Configuration="Release"

      - name: Build
        run: dotnet build --configuration Release --no-restore /warnAsError /nologo /clp:NoSummary

      - name: ReSharper annotations
        uses: VMelnalksnis/resharper-inspect-action@v0.2.4
        with:
          solution: Gnomeshade.sln
          resharper-version: 2022.1.2
          treat-warnings-as-errors: true
