name: Docker version cleanup

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SUN"

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  docker-cleanup:
    name: Docker version cleanup
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'gnomeshade'
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'true'
