name: Nightly Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish API
        run: dotnet publish source/Gnomeshade.Interfaces.WebApi/Gnomeshade.Interfaces.WebApi.csproj -r linux-x64 -c Release --self-contained true -p:PublishSingleFile=true

      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          rm: false
          files: |
            **/publish/Gnomeshade.Interfaces.WebApi
