name: Nightly Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Publish API
        run: >
          dotnet
          publish
          source/Gnomeshade.Interfaces.WebApi/Gnomeshade.Interfaces.WebApi.csproj
          --runtime linux-x64
          --configuration Release
          --self-contained true
          -p:PublishSingleFile=true
          -p:VersionPrefix=0.1.0
          -p:VersionSuffix=nightly
          -p:AssemblyVersion=0.1.0.$Env:GITHUB_RUN_NUMBER
          -p:InformationalVersion=gnomeshade-0.1.0-nightly+sha.$Env:GITHUB_SHA.linux-x64

      - name: Archive published API
        run: 7z a -axr*.json -mx9 -r gnomeshade_linux-x64.zip
        working-directory: source/Gnomeshade.Interfaces.WebApi/bin/Release/net6.0/linux-x64/publish

      - name: Publish desktop application
        run: >
          dotnet
          publish
          source/Gnomeshade.Interfaces.Desktop/Gnomeshade.Interfaces.Desktop.csproj 
          --runtime win10-x64
          --configuration Release
          --self-contained true
          -p:PublishSingleFile=true
          -p:VersionPrefix=0.1.0
          -p:VersionSuffix=nightly
          -p:AssemblyVersion=0.1.0.$Env:GITHUB_RUN_NUMBER
          -p:InformationalVersion=gnomeshade_desktop-0.1.0-nightly+sha.$Env:GITHUB_SHA.linux-x64

      - name: Archive published desktop application
        run: 7z a -mx9 -r gnomeshade_desktop_win-x64.zip
        working-directory: source/Gnomeshade.Interfaces.Desktop/bin/Release/net6.0-windows/win10-x64/publish

      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          rm: true
          files: |
            **/linux-x64/publish/gnomeshade_linux-x64.zip
            **/win10-x64/publish/gnomeshade_desktop_win-x64.zip
