name: Nightly Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest ]
        runtime: [ win10-x64 ]
        project: [ source/Gnomeshade.Interfaces.Desktop/Gnomeshade.Interfaces.Desktop.csproj ]
        build_number: [ ${{ env.GITHUB_RUN_NUMBER }} ]
        archive_command: [ "7z a -mx9 -r gnomeshade_desktop_win-x64.zip" ]
        directory: [ source/Gnomeshade.Interfaces.Desktop/bin/Release/net6.0/win10-x64/publish ]
        artifact: [ "**/win10-x64/publish/gnomeshade_desktop_win-x64.zip" ]
        include:
          - os: ubuntu-latest
            runtime: linux-x64
            project: source/Gnomeshade.Interfaces.WebApi/Gnomeshade.Interfaces.WebApi.csproj
            build_number: ${{ env.GITHUB_RUN_NUMBER }}
            archive_command: zip -r -9 gnomeshade_linux-x64.zip . -x \*.json
            directory: source/Gnomeshade.Interfaces.WebApi/bin/Release/net6.0/linux-x64/publish
            artifact: "**/linux-x64/publish/gnomeshade_linux-x64.zip"

          - os: ubuntu-latest
            runtime: linux-x64
            project: source/Gnomeshade.Interfaces.Desktop/Gnomeshade.Interfaces.Desktop.csproj
            build_number: ${{ env.GITHUB_RUN_NUMBER }}
            archive_command: zip -r -9 gnomeshade_desktop_linux-x64.zip .
            directory: source/Gnomeshade.Interfaces.Desktop/bin/Release/net6.0/linux-x64/publish
            artifact: "**/linux-x64/publish/gnomeshade_desktop_linux-x64.zip"

    name: Build
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.203

      - name: Publish project
        run: >
          dotnet
          publish
          ${{ matrix.project }}
          --runtime ${{ matrix.runtime }}
          --configuration Release
          --self-contained
          -p:PublishSingleFile=true
          -p:AssemblyVersion=0.1.0.${{ matrix.build_number }}
          -p:InformationalVersion=0.1.0-nightly+${{ matrix.runtime }}
          /warnAsError
          /nologo

      - name: Archive published artifacts
        run: ${{ matrix.archive_command }}
        working-directory: ${{ matrix.directory }}

      - name: Upload artifact to releases
        uses: pyTooling/Actions/releaser/composite@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          rm: false
          files: ${{ matrix.artifact }}
