name: Nightly Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Publish API
        run: >
          dotnet
          publish
          source/Gnomeshade.Interfaces.WebApi/Gnomeshade.Interfaces.WebApi.csproj
          --runtime linux-x64
          --configuration Release
          --self-contained true
          -p:PublishSingleFile=true

      - name: Archive published API
        run: >
          zip -r 
          source/Gnomeshade.Interfaces.WebApi/bin/Release/net6.0/linux-x64/publish/gnomeshade_linux-x64.zip
          source/Gnomeshade.Interfaces.WebApi/bin/Release/net6.0/linux-x64/publish/

      - name: Publish desktop application
        run: >
          dotnet
          publish
          source/Gnomeshade.Interfaces.Desktop/Gnomeshade.Interfaces.Desktop.csproj 
          --runtime win10-x64
          --configuration Release
          --self-contained true
          -p:PublishSingleFile=true
          -p:IncludeNativeLibrariesForSelfExtract=true

      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          rm: true
          files: |
            **/linux-x64/publish/gnomeshade_linux-x64.zip
            **/win10-x64/publish/Gnomeshade.Interfaces.Desktop.exe
