name: Release

on:
  push:
    tags: [ v*.*.* ]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest ]
        runtime: [ win10-x64 ]
        project: [ Gnomeshade.Interfaces.Desktop ]
        publish_script: [ "deployment/publish.ps1" ]
        artifact: [ a ]
        include:
          - os: ubuntu-latest
            runtime: linux-x64
            project: Gnomeshade.Interfaces.WebApi
            publish_script: deployment/publish.sh
            artifact: [ b ]

          - os: ubuntu-latest
            runtime: linux-x64
            project: Gnomeshade.Interfaces.Desktop
            publish_script: deployment/publish.sh
            artifact: [ c ]

    outputs:
      artifact1: ${{ steps.artifact-name.outputs.a }}
      artifact2: ${{ steps.artifact-name.outputs.b }}
      artifact3: ${{ steps.artifact-name.outputs.c }}

    name: Build
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.203

      - run: chmod +x ${{ matrix.publish_script }}
        if: matrix.os == 'ubuntu-latest'

      - name: Publish project
        id: publish
        run: >
          ${{ matrix.publish_script }}
          "${{ matrix.project }}"
          "${{ matrix.runtime }}"
          "${{ github.run_number }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.publish.outputs.artifact-name }}
          path: ${{ steps.publish.outputs.artifact }}

      - name: Set artifact output
        id: artifact-name
        run: echo '::set-output name={{ matrix.artifact }}::${{ steps.publish.outputs.artifact-name }}'

  create-release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.one.outputs.artifact1 }}
          
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.one.outputs.artifact2 }}

      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.one.outputs.artifact3 }}

      - name: Create release
        uses: softprops/action-gh-release@v0.1.14
        with:
          draft: true
          prerelease: false
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            *.zip
