name: Release

on:
  push:
    branches: [ master ]
    tags: [ v*.*.* ]
    paths-ignore:
      - '**.md'

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    strategy:
      matrix:
        project:
          - Gnomeshade.Desktop.Installer
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-dotnet@v3.0.1
      - uses: microsoft/setup-msbuild@v1.1

      - run: $env:BUILD_TAG = "-nightly"
        if: ${{ !(startsWith(github.ref, 'refs/tags/')) }}

      - run: $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"

      - name: Cache NuGet packages
        uses: actions/cache@v3.0.10
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-win10-x64-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Publish project
        id: publish
        run: deployment/build.ps1 ${{ matrix.project }}
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ steps.publish.outputs.artifact-name }}
          path: ${{ steps.publish.outputs.artifact }}

  build-linux:
    strategy:
      matrix:
        project:
          - Gnomeshade.Desktop
          - Gnomeshade.WebApi
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-dotnet@v3.0.1
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'source/Gnomeshade.WebApi/Node/package-lock.json'

      - run: echo "BUILD_TAG=-nightly"
        if: ${{ !(startsWith(github.ref, 'refs/tags/')) }}

      - name: Cache NuGet packages
        uses: actions/cache@v3.0.10
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-linux-x64-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Publish project
        id: publish
        run: >
          deployment/publish.sh
          "${{ matrix.project }}"
          "linux-x64"
          "${{ github.run_number }}"
          "-nightly"

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ steps.publish.outputs.artifact-name }}
          path: ${{ steps.publish.outputs.artifact }}
  
  build-deb:
    name: Build debian package
    needs: build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - uses: actions/download-artifact@v3.0.0
        id: download
        with:
          name: Gnomeshade.WebApi_linux-x64.zip

      - name: Install lintian
        run: sudo apt update && sudo apt install lintian

      - name: Build debian package
        run: >
          deployment/debian.sh
          "${{ steps.download.outputs.download-path }}/Gnomeshade.WebApi_linux-x64.zip"
          "${{ github.run_number }}"

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: Gnomeshade.WebApi_linux-x64.deb
          path: "**/*.deb"

  deploy-demo:
    name: Deploy demo app
    needs: build-linux
    runs-on: ubuntu-latest
    env:
      AZURE_APP_NAME: gnomeshade-demo
      AZURE_APP_DOMAIN: 'https://gnomeshade-demo.azurewebsites.net/'
    steps:
      - uses: actions/download-artifact@v3.0.0
        id: download
        with:
          name: Gnomeshade.WebApi_linux-x64.zip

      - run: unzip Gnomeshade.WebApi_linux-x64.zip
      - run: rm Gnomeshade.WebApi_linux-x64.zip

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'

      - uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          app-settings-json: |
            [
                {
                    "name": "ConnectionStrings__Gnomeshade",
                    "value": "Data Source=/tmp/gnomeshade.db",
                    "slotSetting": false
                },
                {
                    "name": "Database__Provider",
                    "value": "Sqlite",
                    "slotSetting": false
                },
                {
                    "name": "Jwt__Secret",
                    "value": "${{ secrets.DEMO_JWT_SECRET }}",
                    "slotSetting": false
                },
                {
                    "name": "Jwt__ValidAudience",
                    "value": "${{ env.AZURE_APP_DOMAIN }}",
                    "slotSetting": false
                },
                {
                    "name": "Jwt__ValidIssuer",
                    "value": "${{ env.AZURE_APP_DOMAIN }}",
                    "slotSetting": false
                }
            ]
  
  update-nightly:
    name: Update nightly release
    needs:
      - build-windows
      - build-linux
      - build-deb
    runs-on: ubuntu-latest
    if: ${{ !(startsWith(github.ref, 'refs/tags/')) }}
    steps:
      - uses: actions/download-artifact@v3.0.0
        id: download
        with:
          path: artifacts

      - name: Upload artifact to nightly release
        uses: pyTooling/Actions/releaser/composite@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          rm: true
          files: |
            ${{ steps.download.outputs.download-path }}/**/*.zip
            ${{ steps.download.outputs.download-path }}/**/*.deb
            ${{ steps.download.outputs.download-path }}/**/*.msi
  
  create-release:
    name: Create release
    needs:
      - build-windows
      - build-linux
      - build-deb
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/download-artifact@v3.0.0
        id: download
        with:
          path: artifacts

      - name: Create release
        uses: softprops/action-gh-release@v0.1.14
        with:
          draft: true
          prerelease: false
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ${{ steps.download.outputs.download-path }}/**/*.zip
            ${{ steps.download.outputs.download-path }}/**/*.deb
            ${{ steps.download.outputs.download-path }}/**/*.msi
